services:
  ICDDB:
    container_name: ICD-DB
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  spectrailtestdataprovider.api:
    container_name: spectrailtestdataprovider.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SpectrailMongoDatabaseSettings:ConnectionString=mongodb://ICDDB:27017"
      - "SpectrailMongoDatabaseSettings:DatabaseName=ICDDB"
      - "SpectrailMongoDatabaseSettings:CollectionName=ICDDatas"
    ports:
      - "8080:8080"
      - "8081:8081"
    
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "7070:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data