services:
  ICDDB:
    image: mongo

  spectrailtestserver.api:
    image: ${DOCKER_REGISTRY-}spectrailtestserver
    build:
      context: .
      dockerfile: SpectrailTestServer/SpectrailTestDataProvider.API/Dockerfile
      
  portainer:
    image: portainer/portainer-ce
    
volumes:
  mongo_data:
  portainer_data: