services:
  ICDDB:
    container_name: ICD-DB
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db
      
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "7070:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8082:8081"  # Expose Mongo Express on host port 8082
    environment:
      - ME_CONFIG_MONGODB_SERVER=ICDDB  # Connect to the MongoDB service
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=false  # Disable basic auth for simplicity (optional)
    depends_on:
      - ICDDB
        
  alstom.spectrail.icd.api:
    container_name: alstom.spectrail.icd.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SpectrailMongoDatabaseSettings:ConnectionString=mongodb://ICDDB:27017"
      - "SpectrailMongoDatabaseSettings:DatabaseName=ICDDB"
      - "SpectrailMongoDatabaseSettings:CollectionName=ICDDatas"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ICDDB
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
