services:
  ICDDB:
    container_name: ICD-DB
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db
    networks:
      - alstom_spectrail_server_network 
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "7070:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - alstom_spectrail_server_network
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8082:8081"  # Expose Mongo Express on host port 8082
    environment:
      - ME_CONFIG_MONGODB_SERVER=ICDDB  # Connect to the MongoDB service
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=false  # Disable basic auth for simplicity (optional)
    depends_on:
      - ICDDB
    networks:
      - alstom_spectrail_server_network    
  alstom.spectrail.icd.api:
    container_name: alstom.spectrail.icd.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SpectrailMongoDatabaseSettings:ConnectionString=mongodb://ICD-DB:27017"
      - "SpectrailMongoDatabaseSettings:DatabaseName=ICDDB"
      - "SpectrailMongoDatabaseSettings:CollectionName=ICDDatas"
      - "Settings__ICD_FOLDER_PATH=DATA/ICDs"
      - "FeatureFlags__EnableChecksumValidation=true"
      - "FeatureFlags__EnableEagerLoading=false"
      - "FeatureFlags__EnableMiddlewarePreloading=true"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ICDDB
    volumes:
      - ${APPDATA:-$HOME/.microsoft}/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA:-$HOME/.aspnet}/Https:/home/app/.aspnet/https:ro
      - ${APPDATA:-$HOME}/SpectrailArtifacts/DATA/ICDs:/home/app/SpectrailArtifacts/DATA/ICDs:ro"
      
    networks:
      - alstom_spectrail_server_network
    ## 🔹 Add Restart Policy (Auto-restart on failure)
    restart: always
    ## 🔹 Add Health Check (Ensure API is running)
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    ## 🔹 Add Logging Options (Limit log size)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Max log size
        max-file: "5"    # Keep last 5 log files
    
    ## 🔹 Add Custom Labels (Useful for Monitoring)
    labels:
      - "maintainer=SUBHASISH BISWAS"
      - "app=Spectrail-ICD-API"
      - "version=1.0"
      - com.docker.compose.project=SpectrailTestServer
      
networks:
  alstom_spectrail_server_network:
    name: alstom_spectrail_server_network  # 👈 Assign a specific network name
    driver: bridge